[package]
name        = "interop-commons-io-bom"
description = "Flix wrappers over the Byte Order Mark classes of Apache Commons IO."
version     = "0.2.2"
flix        = "0.36.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/basis-base"                = "0.2.2"
"github:stephentetley/graded-lib"                = "0.4.0"
"github:stephentetley/interop-base"              = "0.3.1"


[mvn-dependencies]
"commons-io:commons-io" = "2.11.0"
