[package]
name        = "interop-commons-io-bom"
description = "Flix wrappers over the JDK libraries built on top of interop-base."
version     = "0.1.0"
flix        = "0.34.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/basis-base"                = "0.1.0"
"github:stephentetley/graded-lib"                = "0.1.0"
"github:stephentetley/interop-base"              = "0.2.0"


[mvn-dependencies]
"commons-io:commons-io" = "2.11.0"
